LabLink-Project/LabLink-BE

- src/main/java/com/example/lablink/company/controller/CompanyController.java
- src/main/java/com/example/lablink/company/dto/request/CompanyLoginRequestDto.java
- src/main/java/com/example/lablink/company/dto/request/CompanySignupRequestDto.java
- src/main/java/com/example/lablink/company/entity/Company.java
- src/main/java/com/example/lablink/company/exception/CompanyErrorCode.java
- src/main/java/com/example/lablink/company/exception/CompanyException.java
- src/main/java/com/example/lablink/company/exception/CompanyExceptionHandler.java
- src/main/java/com/example/lablink/company/repository/CompanyRepository.java
- src/main/java/com/example/lablink/company/service/CompanyService.java
- src/main/java/com/example/lablink/jwt/JwtUtil.java
- src/main/java/com/example/lablink/message/ResponseMessage.java
- src/main/java/com/example/lablink/security/UserDetailsImpl.java
- src/main/java/com/example/lablink/user/controller/UserController.java
- src/main/java/com/example/lablink/user/entity/User.java
- src/main/java/com/example/lablink/user/entity/UserRoleEnum.java
- src/main/java/com/example/lablink/user/repository/UserRepository.java
- src/main/java/com/example/lablink/user/service/UserService.java
> feat: 유저, 기업 회원가입 및 로그인 구현 완료

- src/main/java/com/example/lablink/category/entity/Category.java
- src/main/java/com/example/lablink/category/exception/CategoryErrorCode.java
- src/main/java/com/example/lablink/category/exception/CategoryException.java
- src/main/java/com/example/lablink/category/exception/CategoryExceptionHandler.java
- src/main/java/com/example/lablink/category/repository/CategoryRepository.java
- src/main/java/com/example/lablink/category/service/CategoryService.java
- src/main/java/com/example/lablink/message/ResponseMessage.java
- src/main/java/com/example/lablink/study/controller/StudyController.java
- src/main/java/com/example/lablink/study/dto/StudySearchOption.java
- src/main/java/com/example/lablink/study/dto/requestDto/StudyRequestDto.java
- src/main/java/com/example/lablink/study/dto/responseDto/StudyDetailResponseDto.java
- src/main/java/com/example/lablink/study/dto/responseDto/StudyResponseDto.java
- src/main/java/com/example/lablink/study/entity/Study.java
- src/main/java/com/example/lablink/study/entity/StudyStatusEnum.java
- src/main/java/com/example/lablink/study/exception/StudyErrorCode.java
- src/main/java/com/example/lablink/study/exception/StudyException.java
- src/main/java/com/example/lablink/study/exception/StudyExceptionHandler.java
- src/main/java/com/example/lablink/study/repository/StudyRepository.java
- src/main/java/com/example/lablink/study/service/StudyService.java
company study CRUD 생성
틀만 잡아 놓은거라 많은 부분 수정 필요함니다
> feat: Create company study CRUD (수정 필요)

- src/main/java/com/example/lablink/LabLinkApplication.java
- src/main/java/com/example/lablink/timestamp/entity/Timestamped.java
timestamp entity 추가하고, LabLinkApplication에 어노테이션 추가했습니다 !
주석처리 해놓은 json파싱, date포멧 어노테이션 중에 사용하시면 됨니당
> 28 feature/timestamp entity

- src/main/java/com/example/lablink/bookmark/controller/BookmarkController.java
- src/main/java/com/example/lablink/bookmark/entity/Bookmark.java
- src/main/java/com/example/lablink/bookmark/repository/BookmarkRepository.java
- src/main/java/com/example/lablink/bookmark/service/BookmarkService.java
> feat: Create bookmark feature

- src/main/java/com/example/lablink/company/controller/CompanyController.java
- src/main/java/com/example/lablink/company/dto/request/CompanyEmailCheckRequestDto.java
- src/main/java/com/example/lablink/company/dto/request/CompanyNameCheckRequestDto.java
- src/main/java/com/example/lablink/company/dto/response/CompanyEmailCheckResponseDto.java
- src/main/java/com/example/lablink/company/dto/response/CompanyNameCheckResponseDto.java
- src/main/java/com/example/lablink/company/exception/CompanyErrorCode.java
- src/main/java/com/example/lablink/company/repository/CompanyRepository.java
- src/main/java/com/example/lablink/company/service/CompanyService.java
- src/main/java/com/example/lablink/config/WebSecurityConfig.java
- src/main/java/com/example/lablink/jwt/JwtAuthFilter.java
- src/main/java/com/example/lablink/jwt/JwtUtil.java
- src/main/java/com/example/lablink/user/controller/UserController.java
- src/main/java/com/example/lablink/user/dto/request/SignupRequestDto.java
- src/main/java/com/example/lablink/user/dto/request/UserEmailCheckRequestDto.java
- src/main/java/com/example/lablink/user/dto/response/UserEmailCheckResponseDto.java
- src/main/java/com/example/lablink/user/entity/User.java
- src/main/java/com/example/lablink/user/entity/UserInfo.java
- src/main/java/com/example/lablink/user/security/UserDetailsServiceImpl.java
- src/main/java/com/example/lablink/user/service/UserService.java
쿠키 전송은 추후 리팩토링 예정
(csrf토큰 및 refresh)
> fix: user company jwt토큰 헤더 전송

- build.gradle
- src/main/java/com/example/lablink/application/controller/ApplicationController.java
- src/main/java/com/example/lablink/application/dto/Request/ApplicationRequestDto.java
- src/main/java/com/example/lablink/application/dto/Response/ApplicationResponseDto.java
- src/main/java/com/example/lablink/application/entity/Application.java
- src/main/java/com/example/lablink/application/exception/ApplicationErrorCode.java
- src/main/java/com/example/lablink/application/exception/ApplicationException.java
- src/main/java/com/example/lablink/application/exception/ApplicationExceptionHandler.java
- src/main/java/com/example/lablink/application/repository/ApplicationRepository.java
- src/main/java/com/example/lablink/application/service/ApplicationService.java
- src/main/java/com/example/lablink/company/exception/CompanyErrorCode.java
- src/main/java/com/example/lablink/company/repository/CompanyRepository.java
- src/main/java/com/example/lablink/company/service/CompanyService.java
- src/main/java/com/example/lablink/config/Swagger2Config.java
- src/main/java/com/example/lablink/message/ResponseMessage.java
- src/main/java/com/example/lablink/study/repository/StudyRepository.java
- src/main/java/com/example/lablink/study/service/GetStudyService.java
- src/main/java/com/example/lablink/study/service/StudyService.java
- src/main/java/com/example/lablink/timestamp/entity/Timestamped.java
- src/main/java/com/example/lablink/user/exception/UserErrorCode.java
- src/main/java/com/example/lablink/user/service/UserService.java
application의 crud 완료
추가적으로 액츄에이터 및 프로메테우스 설정 추가
swagger 추가
> feat : application 구현

- build.gradle
- src/main/java/com/example/lablink/S3Image/dto/S3RequestDto.java
- src/main/java/com/example/lablink/S3Image/dto/S3ResponseDto.java
- src/main/java/com/example/lablink/S3Image/entity/S3Image.java
- src/main/java/com/example/lablink/S3Image/repository/S3ImageRepository.java
- src/main/java/com/example/lablink/S3Image/service/S3UploaderService.java
- src/main/java/com/example/lablink/application/dto/Response/ApplicationResponseDto.java
- src/main/java/com/example/lablink/config/S3Config.java
- src/main/java/com/example/lablink/study/controller/StudyController.java
- src/main/java/com/example/lablink/study/dto/requestDto/StudyRequestDto.java
- src/main/java/com/example/lablink/study/entity/Study.java
- src/main/java/com/example/lablink/study/exception/StudyErrorCode.java
- src/main/java/com/example/lablink/study/service/StudyService.java
> fix:신청서 Response dto 수정

- build.gradle
- src/main/java/com/example/lablink/S3Image/service/S3UploaderService.java
- src/main/java/com/example/lablink/config/S3Config.java
- src/main/java/com/example/lablink/study/service/StudyService.java
s3 image upload error 고쳤습니다 !!!
application.yml 파일의 경로 수정 
`spring.s3.bucket` -> `cloud.aws.s3.bucket`
> fix: s3 image upload error 수정

- src/main/java/com/example/lablink/application/exception/ApplicationErrorCode.java
- src/main/java/com/example/lablink/application/repository/ApplicationRepository.java
- src/main/java/com/example/lablink/application/service/ApplicationService.java
- src/main/java/com/example/lablink/bookmark/repository/BookmarkRepository.java
- src/main/java/com/example/lablink/bookmark/service/BookmarkService.java
- src/main/java/com/example/lablink/study/service/StudyService.java
- src/main/java/com/example/lablink/user/controller/UserController.java
- src/main/java/com/example/lablink/user/entity/Terms.java
- src/main/java/com/example/lablink/user/repository/TermsRepository.java
- src/main/java/com/example/lablink/user/service/TermsService.java
- src/main/java/com/example/lablink/user/service/UserService.java
종속성 제거를 위해 각 service에 find & delete함수 생성,
특이사항으로 userservice에 RequiredArgsConstructor대신 @Autowired, @Lazy 사용해 순환 종속성 오류 해결,
UserController 스웨거 설정.
> feat: 회원탈퇴 추가

- build.gradle
- src/main/java/com/example/lablink/application/controller/ApplicationController.java
- src/main/java/com/example/lablink/application/dto/Request/ApplicationRequestDto.java
- src/main/java/com/example/lablink/application/dto/Response/ApplicationResponseDto.java
- src/main/java/com/example/lablink/application/service/ApplicationService.java
- src/main/java/com/example/lablink/config/Swagger2Config.java
- src/main/java/com/example/lablink/feedback/controller/FeedBackController.java
- src/main/java/com/example/lablink/feedback/dto/Request/FeedBackRequestDto.java
- src/main/java/com/example/lablink/feedback/dto/Response/FeedBackResponseDto.java
- src/main/java/com/example/lablink/feedback/entity/Feedback.java
- src/main/java/com/example/lablink/feedback/repository/FeedBackRepository.java
- src/main/java/com/example/lablink/feedback/service/FeedBackService.java
- src/main/java/com/example/lablink/user/entity/UserInfo.java
api 수정 application-> applications
신청서 접수 클릭 시 나오는 값 api 수정 application->applicationInfo
applicationReqestDto 정보 값 추가
> fix : application api 수정

- build.gradle
- src/main/java/com/example/lablink/LabLinkApplication.java
- src/main/java/com/example/lablink/config/RedisConfiguration.java
- src/main/java/com/example/lablink/config/WebSecurityConfig.java
- src/main/java/com/example/lablink/study/controller/StudyController.java
- src/main/java/com/example/lablink/study/dto/StudySearchOption.java
- src/main/java/com/example/lablink/study/dto/requestDto/StudyRequestDto.java
- src/main/java/com/example/lablink/study/dto/responseDto/LatestSearchKeyword.java
- src/main/java/com/example/lablink/study/dto/responseDto/SearchRankResponseDto.java
- src/main/java/com/example/lablink/study/dto/responseDto/StudyDetailResponseDto.java
- src/main/java/com/example/lablink/study/entity/Study.java
- src/main/java/com/example/lablink/study/exception/StudyErrorCode.java
- src/main/java/com/example/lablink/study/repository/RedisRepository.java
- src/main/java/com/example/lablink/study/repository/StudyRepository.java
- src/main/java/com/example/lablink/study/service/StudySearchService.java
- src/main/java/com/example/lablink/study/service/StudyService.java
> feat: 검색, 인기검색어, 최근 검색 기록 구현

- src/main/java/com/example/lablink/application/controller/ApplicationController.java
- src/main/java/com/example/lablink/application/service/ApplicationService.java
- src/main/java/com/example/lablink/study/dto/responseDto/StudyDetailResponseDto.java
- src/main/java/com/example/lablink/study/entity/Study.java
지원자 수 현황 확인 기능 추가
지원자 수 현황을 통한 정렬 기능 추가
> feat: 지원자 수 현황 확인 기능 추가

- src/main/java/com/example/lablink/application/service/ApplicationService.java
- src/main/java/com/example/lablink/user/exception/UserErrorCode.java
- src/main/java/com/example/lablink/user/service/UserInfoService.java
- src/main/java/com/example/lablink/user/service/UserService.java
기존 EAGER fetch type으로 즉시로딩을 사용했는데 조회 속도 및 성능 부분에서 문제가 될거라 예상하고  LAZY fetch type 으로 변경.
> fix: 기업 각 공고별 신청서 확인 수정

- src/main/java/com/example/lablink/company/controller/CompanyController.java
- src/main/java/com/example/lablink/company/dto/response/ViewMyStudyResponseDto.java
- src/main/java/com/example/lablink/company/repository/CompanyRepository.java
- src/main/java/com/example/lablink/company/service/CompanyService.java
- src/main/java/com/example/lablink/study/service/StudyService.java
새로운 responseDto 생성 후 기존 studyService에 있는 공고찾기 메서드 활용했습니다.
> feat: 내(기업)가 작성한 공고 확인하기

- src/main/java/com/example/lablink/user/controller/UserMyPageController.java
- src/main/java/com/example/lablink/user/dto/request/MyPageCheckRequestDto.java
- src/main/java/com/example/lablink/user/dto/response/UserModifyResponseDto.java
- src/main/java/com/example/lablink/user/entity/User.java
- src/main/java/com/example/lablink/user/entity/UserInfo.java
- src/main/java/com/example/lablink/user/exception/UserErrorCode.java
- src/main/java/com/example/lablink/user/service/UserMyPageService.java
1. 내 정보 수정을 위해 로그인 유저의 비밀번호 확인. -> 2번의 이름, 생년월일에 들어갈 값 반환.
2. 이름 및 기타 정보 수정.
3. 비밀번호 수정
> feat: 마이페이지 정보 수정 완료

- src/main/java/com/example/lablink/feedback/dto/Request/FeedBackRequestDto.java
- src/main/java/com/example/lablink/feedback/dto/Response/DetailFeedBackResponseDto.java
- src/main/java/com/example/lablink/feedback/dto/Response/FeedBackResponseDto.java
- src/main/java/com/example/lablink/feedback/entity/Feedback.java
- src/main/java/com/example/lablink/feedback/repository/FeedBackRepository.java
- src/main/java/com/example/lablink/feedback/service/FeedBackService.java
피드백 전체 리스트에 viewStatus 추가
피드백 상세 정보 보기에 viewStatus 삭제
> fix : FeedBack 기능 수정

- src/main/java/com/example/lablink/user/dto/request/SignupRequestDto.java
- src/main/java/com/example/lablink/user/exception/UserErrorCode.java
- src/main/java/com/example/lablink/user/service/UserService.java
- src/test/java/com/example/lablink/user/service/UserServiceTest.java
- src/test/java/com/example/lablink/user/service/UserServiceTests.java
Mock & InjectMocks 사용한 테스트 코드 작성.
> feat: 회원가입 테스트 코드 작성

- build.gradle
- src/main/java/com/example/lablink/bookmark/controller/BookmarkController.java
- src/main/java/com/example/lablink/bookmark/dto/BookmarkResponseDto.java
- src/main/java/com/example/lablink/bookmark/entity/Bookmark.java
- src/main/java/com/example/lablink/bookmark/repository/BookmarkRepository.java
- src/main/java/com/example/lablink/bookmark/service/BookmarkService.java
- src/main/java/com/example/lablink/chat/controller/RoomController.java
- src/main/java/com/example/lablink/chat/controller/StompChatController.java
- src/main/java/com/example/lablink/chat/dto/ChatMessageDTO.java
- src/main/java/com/example/lablink/chat/dto/ChatRoomDTO.java
- src/main/java/com/example/lablink/chat/entity/ChatMessage.java
- src/main/java/com/example/lablink/chat/entity/ChatRoom.java
- src/main/java/com/example/lablink/chat/mapper/ChatMapper.java
- src/main/java/com/example/lablink/chat/repository/ChatRoomRepository.java
- src/main/java/com/example/lablink/chat/repository/MessageRepository.java
- src/main/java/com/example/lablink/chat/repository/RoomRepository.java
- src/main/java/com/example/lablink/chat/service/ChatRoomService.java
- src/main/java/com/example/lablink/chat/service/ChatService.java
- src/main/java/com/example/lablink/chat/service/RoomService.java
- src/main/java/com/example/lablink/config/ChatConfig.java
- src/main/java/com/example/lablink/config/RedisConfig.java
- src/main/java/com/example/lablink/study/repository/StudyRepository.java
- src/main/java/com/example/lablink/study/service/StudyService.java
- src/main/java/com/example/lablink/user/dto/response/UserDto.java
- src/main/resources/templates/chat/room.html
- src/main/resources/templates/chat/rooms.html
#73
채팅 기능 초안 
북마크 조회 기능 추가 
junit4, Mapper, websocket 추가
> #73 Feature/73 chatting

- .gitignore
- build.gradle
- src/main/java/com/example/lablink/LabLinkApplication.java
- src/main/java/com/example/lablink/feedback/controller/FeedBackController.java
- src/main/java/com/example/lablink/feedback/service/FeedBackService.java
- src/main/resources/logback-spring.xml
> feat : jacoco 기능 추가

- src/main/java/com/example/lablink/company/controller/CompanyController.java
- src/main/java/com/example/lablink/company/service/CompanyService.java
> fix: 컨트롤러 & 서비스 리턴 타입 통일

- src/main/java/com/example/lablink/application/service/ApplicationService.java
- src/main/java/com/example/lablink/user/controller/UserController.java
- src/main/java/com/example/lablink/user/dto/request/SignupRequestDto.java
- src/main/java/com/example/lablink/user/dto/request/UserEmailCheckRequestDto.java
- src/main/java/com/example/lablink/user/dto/request/UserNickNameRequestDto.java
- src/main/java/com/example/lablink/user/entity/User.java
- src/main/java/com/example/lablink/user/exception/UserErrorCode.java
- src/main/java/com/example/lablink/user/repository/UserRepository.java
- src/main/java/com/example/lablink/user/service/UserService.java
- src/test/java/com/example/lablink/user/controller/UserControllerTest.java
- src/test/java/com/example/lablink/user/service/UserServiceTest.java
- src/test/java/com/example/lablink/user/service/UserServiceTests.java
entity에 닉네임컬럼 추가,
회원가입시 닉네임 중복체크 추가,
컨트롤러 mvc 테스트 진행중
> #100 feat: 유저 nickName 추가

- src/main/java/com/example/lablink/company/controller/CompanyController.java
- src/main/java/com/example/lablink/company/dto/request/CompanyLoginRequestDto.java
- src/main/java/com/example/lablink/company/dto/request/CompanySignupRequestDto.java
- src/main/java/com/example/lablink/user/dto/request/LoginRequestDto.java
- src/main/java/com/example/lablink/user/dto/request/SignupRequestDto.java
- src/main/java/com/example/lablink/user/dto/request/UserEmailCheckRequestDto.java
- src/main/java/com/example/lablink/user/entity/User.java
- src/main/java/com/example/lablink/user/service/UserService.java
@Valid를 이용한 유저, 기업 유효성검사.
이메일 - 기본적인 이메일
비밀번호 - 8~20자 사이의 영문, 숫자, 특수문자 조합
핸드폰번호 - "-"를 제외한 11자리 이내의 숫자
> #100 fix: 회원가입 유효성 검사

- src/main/java/com/example/lablink/study/dto/requestDto/StudyRequestDto.java
- src/main/java/com/example/lablink/study/entity/Study.java
- src/main/java/com/example/lablink/study/service/StudyService.java
- src/test/java/com/example/lablink/study/service/StudyServiceTest.java
- src/test/java/com/example/lablink/support/StudyStub.java
StudyService 테스트코드 초안 작성 (junit5, mockito)
> #97 test: Create studyService testcocde

- src/main/java/com/example/lablink/study/controller/StudyController.java
- src/main/java/com/example/lablink/study/service/StudySearchService.java
> #107 feat : delete-lately-searched-list

- src/main/java/com/example/lablink/jwt/JwtUtil.java
> #111 feature: 헤더 닉네임 추가

- src/main/java/com/example/lablink/S3Image/service/S3UploaderService.java
- src/main/java/com/example/lablink/application/dto/Response/ApplicationFromStudyResponseDto.java
- src/main/java/com/example/lablink/application/dto/Response/ApplicationResponseDto.java
- src/main/java/com/example/lablink/application/service/ApplicationService.java
- src/main/java/com/example/lablink/bookmark/service/BookmarkService.java
- src/main/java/com/example/lablink/company/entity/Company.java
- src/main/java/com/example/lablink/study/dto/StudySearchOption.java
- src/main/java/com/example/lablink/study/dto/requestDto/StudyRequestDto.java
- src/main/java/com/example/lablink/study/dto/responseDto/StudyDetailResponseDto.java
- src/main/java/com/example/lablink/study/entity/Study.java
- src/main/java/com/example/lablink/study/service/StudySearchService.java
- src/main/java/com/example/lablink/study/service/StudyService.java
- src/test/java/com/example/lablink/study/controller/StudyControllerTest.java
- src/test/java/com/example/lablink/study/repository/StudyRepositoryTest.java
- src/test/java/com/example/lablink/study/service/GetStudyServiceTest.java
- src/test/java/com/example/lablink/study/service/MockCompanyDetailsService.java
- src/test/java/com/example/lablink/study/service/StudySearchServiceTest.java
- src/test/java/com/example/lablink/study/service/StudyServiceTest.java
- src/test/java/com/example/lablink/support/CompanyStub.java
- src/test/java/com/example/lablink/support/StudyStub.java
- src/test/java/com/example/lablink/support/UserStub.java
- study repeatCount 오타 수정
- application 리팩토링 필요 ! 
- 일단 위에 두개 해놓은 상태인데 코드리뷰하고 리팩토링 필요해보입니다..!
> chore : study repeatCount 오타 및 application DateType 수정

- src/main/java/com/example/lablink/feedback/dto/Response/FeedBackResponseDto.java
- src/main/java/com/example/lablink/feedback/service/FeedBackService.java
- src/main/java/com/example/lablink/scheduler/Scheduler.java
엑셀파일에 유저의 성별,전화번호 추가
유저 엔티티에 엑셀 파일을 보냈는지에 대한 컬럼 추가 필요
> fix : 엑셀 파일 정보 수정

- src/main/java/com/example/lablink/user/dto/request/MyPageCheckRequestDto.java
- src/main/java/com/example/lablink/user/dto/response/UserModifyResponseDto.java
MyPageCheckRequestDto에 `@NoArgsConstructor`추가 !
> refactoring : Update MyPageCheckRequestDto @NoArgsConstructor

- src/main/java/com/example/lablink/bookmark/dto/BookmarkResponseDto.java
- src/main/java/com/example/lablink/study/dto/responseDto/StudyDetailResponseDto.java
- src/main/java/com/example/lablink/study/service/StudySearchService.java
- 스터디 데이터 보내주실때 회사 이름이 누락되는 경우 - 디테일 페이지나, 찜 목록이 해당이 됩니다
- 로그인 안한 유저 검색 안되는 오류 수정
> refactoring

- src/main/java/com/example/lablink/jwt/JwtAuthFilter.java
- src/main/java/com/example/lablink/message/ResponseMessage.java
Token error 에러메시지 형식이 다르고, 에러인데 httpstatus 200 던지는 문제 발생 
-> ResponseMessage 수정해서 해결
> token error 에러메시지 오류

- src/main/java/com/example/lablink/jwt/JwtAuthFilter.java
- src/main/java/com/example/lablink/message/ResponseMessage.java
- src/main/java/com/example/lablink/user/dto/response/UserModifyResponseDto.java
Token error 에러메시지 형식이 다르고, 에러인데 httpstatus 200 던지는 문제 발생
-> ResponseMessage 수정해서 해결
> Token error 에러메시지 수정

- src/test/java/com/example/lablink/user/controller/UserControllerTest.java
- src/test/java/com/example/lablink/user/service/TermsServiceTest.java
- src/test/java/com/example/lablink/user/service/UserInfoServiceTest.java
UserInfoServiceTest 및 TermsService 테스트코드 작성
> #126 test: UserInfoServiceTest 테스트코드 작성

- src/main/java/com/example/lablink/application/dto/Request/ApplicationRequestDto.java
- src/main/java/com/example/lablink/application/dto/Response/ApplicationFromStudyResponseDto.java
- src/main/java/com/example/lablink/application/service/ApplicationService.java
- src/main/java/com/example/lablink/company/dto/response/ViewMyStudyResponseDto.java
- src/main/java/com/example/lablink/company/service/CompanyService.java
- src/main/java/com/example/lablink/scheduler/Scheduler.java
- src/main/java/com/example/lablink/study/service/StudyService.java
- src/main/java/com/example/lablink/user/dto/request/MyPageCheckRequestDto.java
- src/main/java/com/example/lablink/user/dto/response/MyLabResponseDto.java
- src/main/java/com/example/lablink/user/dto/response/UserModifyResponseDto.java
- src/main/java/com/example/lablink/user/entity/Terms.java
- src/main/java/com/example/lablink/user/entity/User.java
- src/main/java/com/example/lablink/user/service/UserMyPageService.java
- src/test/java/com/example/lablink/study/service/StudyServiceTest.java
date타입 통일화
terms 소프트 delete,
내 신청서 date 타입 수정
studyservice 중복 메서드 제거
공고별 신청서 확인 수정
companyservice 수정
UserInfoServiceTest 및 TermsService 테스트코드 작성
> chore: 부분 수정

- src/main/java/com/example/lablink/user/entity/User.java
- src/main/java/com/example/lablink/user/entity/UserInfo.java
- src/main/java/com/example/lablink/user/kakao/service/KakaoService.java
- src/main/java/com/example/lablink/user/service/UserInfoService.java
카카오 로그인 userinfo 연결
user entity의 kakaoId null 허용
> #143 fix : 카카오 로그인 userinfo 연결

- src/main/java/com/example/lablink/feedback/repository/FeedBackRepository.java
- src/main/java/com/example/lablink/feedback/service/FeedBackService.java
- src/main/java/com/example/lablink/scheduler/Scheduler.java
- src/main/java/com/example/lablink/study/entity/Study.java
- src/main/java/com/example/lablink/study/repository/StudyRepository.java
기능이 정상적으로 작동하지 않아 주석 처리하여 merge
> feat :  emailSedExcel 기능 스케레톤 코드

- src/main/java/com/example/lablink/user/service/UserService.java
> fix: userService 회원탈퇴 반복문 수정

- src/main/java/com/example/lablink/jwt/JwtUtil.java
기업 회원가입시 클라이언트로 보내는 jwt 토큰에 기업 이름 추가
> fix: 기업 회원가입 수정

- src/main/java/com/example/lablink/study/controller/StudyController.java
- src/main/java/com/example/lablink/study/repository/StudyRepository.java
- src/main/java/com/example/lablink/study/repository/StudySearchQueryRepository.java
- src/main/java/com/example/lablink/study/service/StudySearchService.java
limit, offset로 발생했던 문제들 수정 
- queryDSL 작동안되던 이슈 수정 
- native query 방금 작성한 공고 검색 안되는 이슈 해결
> #159 feat: 검색 기능 queryDSL로 변경

- src/main/java/com/example/lablink/bookmark/entity/Bookmark.java
- src/main/java/com/example/lablink/user/repository/UserRepository.java
- src/main/java/com/example/lablink/user/service/UserService.java
- src/test/java/com/example/lablink/user/service/UserServiceTest.java
> test: userService 회원탈퇴 테스트코드 수정

- src/test/java/com/example/lablink/user/service/UserServiceTest.java
> chore: ci cd 테스트 진행.

- src/main/java/com/example/lablink/domain/study/repository/StudySearchQueryRepository.java
1. 유저, 기업 회원가입시 이메일 체크dto 하나로 통일,
2. 모든 패키지 구조 수정
> fix: 패키지 구조 수정

- src/main/java/com/example/lablink/domain/user/dto/response/MyLabResponseDto.java
MyLabResponseDto viewStatus, approvalStatus 자리 바뀐 이슈 해결 및 기업명 추가
> #181 refactor: MyLabResponseDto 리팩토링

- src/main/java/com/example/lablink/domain/bookmark/dto/BookmarkResponseDto.java
- src/main/java/com/example/lablink/domain/bookmark/entity/Bookmark.java
refactor : BookmarkResponseDto 수정
> refactor : BookmarkResponseDto 수정

- src/main/java/com/example/lablink/domain/feedback/service/FeedBackService.java
- src/main/java/com/example/lablink/domain/study/exception/StudyErrorCode.java
feedBack에서 company와 study id 검증 로직 수정
> fix : feedBack 로직 수정

- src/main/java/com/example/lablink/domain/user/kakao/service/KakaoService.java
- src/main/java/com/example/lablink/global/config/WebSecurityConfig.java
> #181 refactor : 배포 url로 변경

- src/test/java/com/example/lablink/user/service/UserServiceTest.java
> fix: 회원가입 수정

- src/main/java/com/example/lablink/domain/user/entity/User.java
- src/main/java/com/example/lablink/domain/user/kakao/dto/KakaoUserInfoDto.java
- src/main/java/com/example/lablink/domain/user/kakao/service/KakaoService.java
> #181 refactor : kakao 로그인 email 삭제

- src/main/java/com/example/lablink/domain/user/entity/User.java
- src/main/java/com/example/lablink/domain/user/kakao/controller/KaKaoUserController.java
- src/main/java/com/example/lablink/domain/user/kakao/dto/KakaoUserInfoDto.java
- src/main/java/com/example/lablink/domain/user/kakao/service/KakaoService.java
> kakao 로그인 email 삭제

- src/main/java/com/example/lablink/domain/application/dto/Response/ApplicationFromStudyResponseDto.java
> fix: 공고별 신청서 승인 거절 수정

- src/main/java/com/example/lablink/domain/user/controller/UserController.java
- src/main/java/com/example/lablink/domain/user/entity/RefreshToken.java
- src/main/java/com/example/lablink/domain/user/exception/UserErrorCode.java
- src/main/java/com/example/lablink/domain/user/google/controller/OauthController.java
- src/main/java/com/example/lablink/domain/user/kakao/controller/KaKaoUserController.java
- src/main/java/com/example/lablink/domain/user/repository/RefreshTokenRepository.java
- src/main/java/com/example/lablink/domain/user/service/UserService.java
- src/main/java/com/example/lablink/global/jwt/JwtUtil.java
> #222 feature: 유저 RefreshToken 구현

- src/main/java/com/example/lablink/domain/user/service/UserService.java
1. 회원탈퇴 속도 개선 측정 및 노션 개선 사항에 result 작성 완료.
> fix: 회원탈퇴 실행 속도 측정

- src/main/java/com/example/lablink/domain/user/service/UserService.java
RefreshToken 쿠키에 담기지 않는 문제 수정중
> #222 fix: RefreshToken 수정

- src/main/java/com/example/lablink/domain/user/dto/response/MyLabResponseDto.java
- src/main/java/com/example/lablink/domain/user/service/UserService.java
1. 신청한 목록 시간 측정 및 팀 노션에 result 생성
> fix: 마이페이지 수정

- src/main/java/com/example/lablink/domain/company/entity/Company.java
- src/main/java/com/example/lablink/global/jwt/JwtUtil.java
1. 기업 로그인 이후 바로 탈퇴는 되었음. 
2. 기업 공고 작성 이후 회원탈퇴 안됌.
3. study Entity에는 soft delete설정을 하고 Company Entity에 soft delete 설정을 하지 않아서 500에러 발생.
> fix: 기업 회원탈퇴 수정

- src/main/java/com/example/lablink/domain/study/service/StudySearchService.java
- src/main/java/com/example/lablink/domain/study/service/StudyService.java
- src/main/java/com/example/lablink/global/config/MapperConfig.java
- src/main/java/com/example/lablink/global/config/RedisConfig.java
> redis cache

- src/main/java/com/example/lablink/domain/study/entity/SearchRankKeyword.java
- src/main/java/com/example/lablink/domain/study/repository/SearchRankKeywordRepository.java
- src/main/java/com/example/lablink/domain/study/service/StudyMapper.java
- src/main/java/com/example/lablink/domain/study/service/StudyMapperImpl.java
- src/main/java/com/example/lablink/global/scheduler/Scheduler.java
스케줄러를 이용해서 redis의 데이터 주기적으로 rds에 저장
> #251 feat : 스케줄러를 이용해서 redis의 데이터 주기적으로 rds에 저장

- src/main/resources/logback-spring.xml
운영체제 마다 log 파일 위치 수정 해줘야함 ㅜ 
log file 위치 수정
> #251 refactor : log file 위치 수정

- src/main/java/com/example/lablink/domain/user/dto/response/MyLabResponseDto.java
- src/test/java/com/example/lablink/domain/company/service/CompanyServiceTest.java
- src/test/java/com/example/lablink/user/service/UserServiceTest.java
> #264 test: companyService 테스트 코드 작성 진행중

- src/test/java/com/example/lablink/domain/user/service/UserMyPageServiceTest.java
> #273 test: userMyPageService 테스트 코드 작성중

- src/test/java/com/example/lablink/domain/user/service/TermsServiceTest.java
- src/test/java/com/example/lablink/domain/user/service/UserInfoServiceTest.java
- src/test/java/com/example/lablink/domain/user/service/UserMyPageServiceTest.java
- src/test/java/com/example/lablink/domain/user/service/UserServiceTest.java
> #273 test: user 도메인 커버리지 약 80% 완료

- src/test/java/com/example/lablink/domain/application/service/ApplicationServiceTest.java
> #287 test: application 테스트 코드 작성중
